# Generated by Django 3.2 on 2021-04-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("books", "0003_auto_20210410_1231")]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="category",
            field=models.CharField(
                choices=[
                    ("fiction", "Fiction"),
                    ("regular", "Regular"),
                    ("novel", "Novel"),
                ],
                default="regular",
                max_length=7,
            ),
        )
    ]
